name: Build & test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test:
    name: Test splitcron

    runs-on:
      - ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout splitcron repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Dry-run split jobs
        run: go run . --dry-run --verbose
